<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="unittest.suite._ErrorHolder-20220524093311" tests="1" file="unittest/suite.py" time="0.000" timestamp="0001-01-01T00:00:00" failures="0" errors="1" skipped="0">
	<testcase classname="" name="tearDownClass (__main__.RegisterAccountTest)" time="0.000" timestamp="0001-01-01T00:00:00" file="UTYourStore\Tests\test1_register.py" line="47">
		<error type="AttributeError" message="type object 'RegisterAccountTest' has no attribute 'get'"><![CDATA[Traceback (most recent call last):
  File "c:\Python\Selenium\UTYourStore\Tests\test1_register.py", line 25, in tearDownClass
    clear_browser_data.clear_browser_data()
  File "C:\Python\Selenium\UTYourStore\Utilities\utilities.py", line 17, in clear_browser_data
    self.driver.get('chrome://settings/clearBrowserData')
AttributeError: type object 'RegisterAccountTest' has no attribute 'get'
]]></error>
	</testcase>
</testsuite>
